### ISSUE TITLE
libvulkan-1.dll missing but no fix-libvulkan-1.dll-missing-error.cmd

### ISSUE THREAD

**Issue by grochoge** [pal1000/mesa-dist-win#113]
I attempted to perform a per-app install for a 32-bit application that uses OpenGL with [mesa3d-22.1.6-release-mingw.7z](https://github.com/pal1000/mesa-dist-win/releases/download/22.1.6/mesa3d-22.1.6-release-mingw.7z). In this case within Windows Sandbox for testing.

The application fails to launch due to vulkan-1.dll not being found.

The README says to run `fix-libvulkan-1.dll-missing-error.cmd`, but this file does not existing within the package.

**Comment by grochoge** [comment]
Would it be best to just modify the readme to direct people to https://vulkan.lunarg.com/sdk/home to download the runtime directly? That did fix the issue for me.

**Comment by pal1000** [comment]
I actually have this in readme, but you stopped at the wrong paragraph in known issues section. This is the right paragraph:

> Mesa `opengl32.dll` from MinGW package depends on [Vulkan runtime](https://vulkan.lunarg.com/sdk/home#windows) since 21.0.0. This is an [upstream regression](https://gitlab.freedesktop.org/mesa/mesa/-/issues/3855) introduced when zink driver was patched to support Windows.

This issue was fixed in Mesa 22.2. You can try 22.2.0-rc2 if you want.

As for `fix-libvulkan-1.dll-missing-error.cmd` that's only needed when Mesa3D zink driver is built with MSYS2 MinGW-W64 vulkan-devel group instead of LunarG Vulkan SDK.
I haven't been doing so for months, specifically since this [patch](https://github.com/msys2/MINGW-packages/commit/866dde036c4ef7921da2f3cda3cd3a15b9df9b0f) landed in MSYS2. Now if you try to use a Mesa build with MSYS2 MinGW-W64 vulkan-devel group it crashes with unresolved symbols when trying to load LunarG Vulkan runtime.
