### ISSUE TITLE
mesa is slow on windows to compared to linux

### ISSUE THREAD

**Issue by wesleyvanneck** [pal1000/mesa-dist-win#12]
am using pre compiled modules and its slow any ideas how to fix this

**Comment by wesleyvanneck** [comment]
am using amd ryzen 2200G with vega 8

**Comment by wesleyvanneck** [comment]
and am using windows 8.1

**Comment by pal1000** [comment]
On windows only the software rendering stack is available. So no GPU acceleration. That's the difference. On Linux there is Mesa3D radeonsi driver for AMD GPUs which is hardware accelerated and available by default. There hasn't been hardware acceleration support for Windows in Mesa3D since Windows 9x/Me era. So Mesa3D skipped NTDDM and XPDDM. Now Windows graphics drivers use WDDM and there is no support for it in Mesa3D either. So in short there is nothing I can do.
