### ISSUE TITLE
binary package with .lib and headers

### ISSUE THREAD

**Issue by joa-quim** [pal1000/mesa-dist-win#14]
Hi,

Would it be possible to make an installer that includes also the libs and the headers? I'm trying to port a unix program that uses the GLX API and need them while building that other program.

Thanks

**Comment by pal1000** [comment]
I'll look into it. It shouldn't be hard now that I am using forfiles to copy from mesa build folder to distribution folder. In the most fortunate case is just 2 lines of code for each build system (scons and upcoming meson build respectively).

If you have time and if you can set the build environment for Mesa3D and build it you can look yourself into it. The relevant code is in `buildscript/modules/dist.cmd`.
Anyway I'll take care of it by next release.

Some extra: If you are using cross-compilation with Mingw-w64 for the porting operation you might have problems. I heard that MSVC made libraries and Mingw-w64 don't mix well sometimes.

**Comment by joa-quim** [comment]
Thanks,
Yes I thought in trying the build myself but not much time now and all that involves building llvm takes awful long times.
And no, no MingW. All in VisualStudio.

**Comment by pal1000** [comment]
You'll find the libraries and headers in the development pack archive. Good luck with your porting project.

**Comment by joa-quim** [comment]
Hi, thanks a lot for this ... but I have an issue with them. What I need are functions from the GLX API (glXChooseVisual, glXCreateContext, glXMakeCurrent, etc) but I can't find them in your package. The source code has a ``glx.h`` but this one is neither in the package. Is this a separate thing that is not build by your scripts?

**Comment by pal1000** [comment]
Well since you depend on GLX API and Visual Studio build of Mesa is a native build it means it only contains GDI, the Windows native graphics API.  It means you need headers and libraries from a cross-compiled build of Mesa - either mingw, msys2 or cygwin which means I can't help you because building Mesa in any of those environments is even more difficult than a native build.  However you may find pre-built libraries and build generated headers on msys2 and cygwin package catalog. Unfortunately cygwin is still at Mesa 18.0.5 and Msys2 at 18.0.2.

**Comment by joa-quim** [comment]
Appreciate your help. I'll look at an eventual msys build but this is nor crucial anyway. Built most of the code I wanted. Only one left depends on GLX.
