### ISSUE TITLE
Usage with Android emulator on Azure Windows 10 virtual machine?

### ISSUE THREAD

**Issue by Lelelo1** [pal1000/mesa-dist-win#26]
After downloading `mesa3d-19.1.3-release-mingw.exe`-> unzipping -> Running`systemwidedeploy.cmd` and selecting `6. Update system-wide deployment`. The drivers on my Azure Windows 10 vm don't appear to be updated. Running Android emulator I get the following message:

![AndroidEmulatorWithMesa](https://user-images.githubusercontent.com/42244983/62010068-4130ab80-b166-11e9-86d3-84f4efb4e66d.png)

I was expecting the *Microsoft Basic Render Driver* to change?

**Comment by pal1000** [comment]
System wide deployment tool only replaces OpenGL user-mode driver that comes with Microsoft Basic Display Adapter. It doesn't touch the device identifier and it looks like Android emulator looks for that identifier only and makes bad assumptions about what OpenGL support is available. 
You can use a software like GPU Caps Viewer to check if Mesa3D is up to date as it provides more precise information and you'll understand better what I am trying to explain by looking at GPU and OpenGL tabs.

**Comment by Lelelo1** [comment]
I don't see any mentioning of Mesa3D using GPU Caps Viewer:

![OpenGL](https://user-images.githubusercontent.com/42244983/62064966-51ac5900-b22e-11e9-8747-d6e26bbdabf6.png)

**Comment by pal1000** [comment]
It looks like Mesa3D is not installed on your environment. You need to use option 1 or 2 to install Mesa3D desktop OpenGL drivers. Option 6 only updates you from an older version. If no Mesa3D driver is installed it does nothing. I may consider implementing an error message when attempting to update with no driver installed to signal the failure.

**Comment by Lelelo1** [comment]
Using the first option it was installed successfully:

![OpenGlTabSuccess](https://user-images.githubusercontent.com/42244983/62119332-9fbd6d00-b2bf-11e9-9587-ca27b19c2a4c.png)

![GPUTabSuccess](https://user-images.githubusercontent.com/42244983/62119400-c1b6ef80-b2bf-11e9-864e-61a68c5204a4.png)

But get I the same error message `GPU Driver Issue` as before when starting the emulator.

I also just want to mention that there was a complaint when installing with the 2 option: `C:\Users\Me\Desktop\Mesa\x64\swr*.dll
The system cannot find the file specified.` That file was not included in the `mesa3d-19.1.3-release-mingw.exe`.

**Comment by pal1000** [comment]
Mingw binaries don't include swr because it fails to build so I'll fix that harmless error too. 

As for your case I think android emulator only looks at the device identifier and mistakenly believes you have insufficient OpenGL support. It may however require OpenGL 3.3. I don't know its requirements. To get OpenGL 3.3 Core profile include
`@set MESA_GL_VERSION_OVERRIDE=3.3`
in a batch script that opens android emulator.

**Comment by Lelelo1** [comment]
I ran `@set MESA_GL_VERSION_OVERRIDE=3.3` prior to `emulator -avd androidemulatorapi28` (which starts the emulator) in cmd. And I get the same error.

 I also read in the [android docs](https://developer.android.com/studio/run/emulator-acceleration) - there is a deprecated `-gpu mesa` flag. Running with this flag I get:

> androidEmuglConfigInit failed. OpenGLES emulation failed to intialize. Please consider the following troubleshooting steps: ...

**Comment by pal1000** [comment]
I looked at the docs you linked and it looks like I guessed it correctly.  The android emulator reads the device name and thinks it doesn't have enough OpenGL support for `-gpu host` mode so it falls back to a software rendering mode either angle_indirect over Microsoft WARP or swiftshader_indirect.
It looks like you have to explicitly tell it to use Mesa:
`@set MESA_GL_VERSION_OVERRIDE=3.3`
`@emulator -avd androidemulatorapi28 -gpu host`.

**Comment by Lelelo1** [comment]
I get the same error.

In cmd console:
> emulator: WARNING: Your GPU drivers may have a bug. If you experience graphical issues, please consider switching to software rendering.

And a couple of `dsound` errors I believe I also got before in cmd console. Could it actually be the cause of the crash? 
...
> audio: Failed to create voice `adc' 
emulator\qemu\windows-x86_64\qemu-system-x86_64.exe: error while loading state for instance 0x0 of device 'goldfish_pipe'
The GUI error message complain about GPU driver though.

Did I mention the size of this VM don't have a GPU?

**Comment by pal1000** [comment]
I configured my PC to be as close as it can be to your Azure VM:
- disabled GPU driver in device manager;
- installed Android Studio with version 29 of Platform, SDK and emulator.
and I can reproduce this message
![AndroidEmulatorWithMesa](https://user-images.githubusercontent.com/42244983/62010068-4130ab80-b166-11e9-86d3-84f4efb4e66d.png)
However this is only a warning. It tells you are using a render driver that is blacklisted based on its name. Click OK and the emulated android device will boot just fine. It is impossible to avoid seeing it at least once in your environment because Microsoft Basic Render Driver is blacklisted.
Mesa3D on windows doesn't change the render driver name regardless of having working GPU or not so it's still identified as Microsoft Basic Render Driver.
However you can change the GPU mode in command line if you don't want the default fallback which I think is -`gpu swiftshader_indirect` which probably is sub-optimal, it was for me. 
As you installed Mesa3D you can run the emulator with `-gpu host` option to use Mesa3D llvmpipe driver and refusing to fallback altogether and use the hardware rendering mode anyway and that's why you get this warning in the log:
> emulator: WARNING: Your GPU drivers may have a bug. If you experience graphical issues, please consider switching to software rendering.

This warning means you are using a blacklisted render device at your own risk. But since we use Mesa3D the danger highlighted by the warning is avoided.  Mesa3D was slightly faster than default fallback on my system.

You can also use `-gpu angle_indirect` to use Microsoft WARP Direct3D driver which comes with Windows. This option was fastest on my system and it doesn't use Mesa3D at all.

`-gpu mesa` is completely broken, no wonder it's deprecated. It always crashes the emulator.  It uses a Mesa3D build done by Google that it's installed with the emulator in `%LOCALAPPDATA%\Android\Sdk\emulator\lib64\gles_mesa` so it completely ignores my build if installed. Also it's very peculiar how that build was done. The DLL is over 60 MB in size, way larger than usual. Maybe it is a debug build by mistake, but I can only speculate.

**Comment by Lelelo1** [comment]
It still not working.

I turned off the audio: https://stackoverflow.com/questions/40272884/running-android-emulator-with-noaudio-option-returns-qemu-system-i386-exe-au. Which made the audio error messages go away.

And I am getting:
> Critical: UpdateLayeredWindowIndirect failed for ptDst=(164, 27), size=(300x21), dirty=(300x21 0, 0) (A device attached to the system is not functioning.) ((null):0, (null))INFO: QtLogger.cpp:66: Critical: UpdateLayeredWindowIndirect failed for ptDst=(164, 27), size=(300x21), dirty=(300x21 0, 0) (A device attached to the system is not functioning.) ((null):0, (null))

**Comment by pal1000** [comment]
I don't know what's wrong in your environment, but you are definitely not alone with this issue as there are plenty Google search results for `UpdateLayeredWindowIndirect` in connection to Android AVD and Android Studio.

**Comment by Lelelo1** [comment]
`UpdateLayeredWindowIndirect` seem to have come from not cold booting indeed. Doing it removes that error.

Now, running with `-gpu angle_indirect`- gives no error or warning about divers in cmd nor the gui message driver complaint (in contrary to other gpu flags). But the screen of the emulator stays black regardless

**Comment by pal1000** [comment]
Try all 3 applicable GPU modes to your environment -  `-gpu angle_indirect`, `-gpu host` (requires Mesa3D) and `-gpu swiftshader_indirect`. Make sure you cold boot when you change the GPU mode as that could explain why you stuck in black screen. Maybe  `-gpu angle_indirect` doesn't work over your remote display connection.

**Comment by Lelelo1** [comment]
`-gpu angle_indirect`: No error. Black screen.

`-gpu host` (with mesa installed): No error. Black screen. And the following warning:
> emulator: WARNING: Your GPU drivers may have a bug. If you experience graphical issues, please consider switching to software rendering.

`-gpu swiftshader_indirect` No error. Back screen.

**Comment by pal1000** [comment]
What version of android studio are you running? Is it 3.4.2. Can you try an AVD with Android Q (API 29)? That's what I used when I tested.

**Comment by Lelelo1** [comment]
I have tried both Visual Studio and Android Studio. I cd into the folder where `emulator.exe` is and run the commands. Running via the IDEs also doesn't work.

**Comment by pal1000** [comment]
I did my best to help you but it looks like this problem seams to exceed my graphics driver usage debugging expertise. Maybe you'll find help elsewhere.

**Comment by XiaobinZhao** [comment]
@Lelelo1 you solved the problem at the end ? i guess the point is your computer is an Azure Windows 10 virtual machine. Android emulator need kvm-qemu start a virtual machine as the emulator ,that is virtual nested.
