### ISSUE TITLE
[Project Unrelated] WineD3D Build?

### ISSUE THREAD

**Issue by opain-replika** [pal1000/mesa-dist-win#43]
Recently read on Federico Dossena's page that he's busy lately and so I think WineD3D builds are not updated.
I'm not sure wined3d ver 6 released (it's rc6 on fdossena.org)
Nevertheless could you create a build of wined3d for windows?

P.S. sorry I didn't know how else to contact you..
P.P.S. Much thanks for both your swiftshader and mesa build!

**Comment by opain-replika** [comment]
Actually on fdossena website rc5 is latest, not rc6.
Also it seems Wine version 6 stable has been released yesterday.

**Comment by pal1000** [comment]
Here is the build scriipt that Federico uses: https://github.com/adolfintel/wined3d4win
It requires Debian Linux.

**Comment by oscarbg** [comment]
WineD3D 6.0 builds are up!

one wish is to improve on WineD3D for Windows to support new Vulkan backend..
note is if WineD3D4Win patches can be enhanced to support new WineD3D Vulkan backend on Wine 6.0 on Windows too.. or will require patches on Wine itself..

I say because on Linux the WineD3D Vulkan backend requires two things:

*Present libvkd3d-shader.so.1 library on system (built from VKD3D Wine repo: https://source.winehq.org/git/vkd3d.git/)
checked it works..
don't know if WineD3D Vulkan code is ready for Windows support (i.e. searching for libvkd3d-shader.dll)
and also don't know, if when you build WineD3D for Windows, WineD3D Vulkan being enabled or not depends on configure step finding (i.e. being present on build system) libvkd3d-shader.dll or not..
WineHQ VKD3D is somewhat difficult to build on Windows (for obtaining libvkd3d-shader.dll) using native compiler but perhaps easy to crosscompile with similar patches as WineD3D4Win..

*enabling it needs modifying HKEY_CURRENT_USER\Software\Wine\Direct3D "renderer" (REG_SZ) to "vulkan" instead of default "gl"
see https://www.winehq.org/announce/6.0:
> New or modified HKEY_CURRENT_USER\Software\Wine\Direct3D registry keys:
>   - "renderer" (REG_SZ)
>     The backend API to target. This existing setting has an additional
>     valid value in this release: "vulkan". Possible values are now
>     "gl" (default) for OpenGL, "gdi" or "no3d" for GDI, and "vulkan"
>     for Vulkan.

Curious how this can be selected/toggled from Windows as WineD3D4Win doesn't expose Wine registry(?).. would be good to select via some enviromental variable (for ex. set WINED3D_RENDERER=vulkan or WINED3D_VULKAN= 0 or 1)

**Comment by opain-replika** [comment]
The wined3d builds on fdossena.com are updating so closing this.
