### ISSUE TITLE
include and lib folders are empty in mesa3d-22.0.0-r2-development-pack-msvc

### ISSUE THREAD

**Issue by zk-talentech** [pal1000/mesa-dist-win#91]
Thanks for maintaining this Win distribution of Mesa.
This may be a stupid question: shouldn't I find .h and .lib files in the dev-pack so I can include and link them in a project? Why these folders are empty? Thanks again.

**Comment by pal1000** [comment]
> This may be a stupid question: shouldn't I find .h and .lib files in the dev-pack so I can include and link them in a project? Why these folders are empty?

Not all folders are empty, but most are. Your question isn't stupid at all. I guess it's about time I use Meson build install command to handle libraries and headers deployment but it's tricky so I don't regress deployment of everything else. In any casse it will take some time.

**Comment by zk-talentech** [comment]
Thanks for reply. So for now I need to build Mesa to get those .h and .lib files?

**Comment by pal1000** [comment]
Most headers used in development are actually in the source code, so you just need the source code for headers.
As for libs just extract the development pack and then search with Windows explorer for .lib files in either lib\x64 or lib\x86 folders depending on ABI you want to use, then copy o move everything found to a location of your choice. 

I'll make improvements to replicate what Meson install does more accurately by next release.

I haven't been using Meson install directly because it deploys everything and you can't tell not to deploy certain things which makes it incompatible with multipass builds. Also you can't to deploy what's possible when isolated components fail to build, like clover for 32-bit, for example.

**Comment by zk-talentech** [comment]
Thanks for the answer. It seems Mesa only implements OpenGL ES 1.1 and OpenGL ES 2.0. Google has a OpenGL ES implementation [ANGLE](https://github.com/google/angle) which supports 3.x. Do you think ANGLE can work on top of Mesa OpenGL?

**Comment by zk-talentech** [comment]
Thanks for the answer!
