### ISSUE TITLE
How do I use GLonD3d12 in minecraft?

### ISSUE THREAD

**Issue by kleinermob** [pal1000/mesa-dist-win#98]

**Comment by pal1000** [comment]
- Download MSVC release package;
- Deploy Mesa3D desktop OpenGL driver using per app deployment into Minecraft's Java bin folder (you may need to run it once without Mesa3D to find its location using Open file location in task manager on Java process);
- GLonD3D12 is used by default if you are running Windows 10.0.19041.488 or newer and have at least a GPU with driver supporting D3D12 feature level 11 or higher
- Otherwise it can run in software rendering mode by setting these environment variables before running Minecraft:
````
@set GALLIUM_DRIVER=d3d12
@set LIBGL_ALWAYS_SOFTWARE=1
````

**Comment by qinlili23333** [comment]
I recorded a video tutorial last year, but in Chinese. Maybe helpful for u if u can read Chinese text.
https://www.bilibili.com/video/BV1e3411z7Ld/

And i don't recommand to run minecraft in d3d12, since that there is a CPU single core bottle neck that limit the framerate at about 15fps even with a 11800H/RTX3060 high-end laptop. Zink(vulkan translation) usually works better that it can achive almost 60fps.

**Comment by kleinermob** [comment]
@qinlili23333 what is this java version you are using
